dependencies:
- name: elasticsearch
  version: "6.7.0"
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: kibana
  version: "6.7.0"
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: fluent-bit
  version: "1.2.2"
  repository: "https://kubernetes-charts.storage.googleapis.com"
