dependencies:
- name: elasticsearch
  version: 1.30.0
  repository: https://kubernetes-charts.storage.googleapis.com
- name: kibana
  version: 3.2.3
  repository: https://kubernetes-charts.storage.googleapis.com
- name: fluent-bit
  version: 2.5.0
  repository: https://kubernetes-charts.storage.googleapis.com
